name: flutter_final_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  table_calendar: ^3.1.2
  percent_indicator: ^4.0.1
  text_to_speech: ^0.2.3
  speech_to_text: ^6.6.2
  url_launcher: ^6.3.0
  syncfusion_flutter_calendar: ^26.2.8
  http: ^0.13.5
  flutter_tts: ^3.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
 
